version: '2'
services:
  mongo:
    container_name: mongo
    build: docker/mongo
    ports:
      - "27017:27017"
  api:
    container_name: api
    build: docker/api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
